apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: prometheus
  name: prometheus-kube-state-metrics
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: telemetry
    port: 81
    protocol: TCP
    targetPort: 8081
  selector:
    app: prometheus
  sessionAffinity: None
  type: ClusterIP